name: Test Action With Param

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Action With Param
      uses: libresource/action-template@master
      with:
        param-example: 'Hello GitHub!'
