name: Test Action With Param

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Action With Param
      uses: libresource/action-template@v0.2.0
      with:
        param-example: 'Hello GitHub!'
